[package]
name = "aes"
version = "0.1.0"
edition = "2021"

[dependencies]
jolt-sdk = { workspace = true, features = ["host"] }
tracing-subscriber.workspace = true
tracing.workspace = true
jolt-inlines-aes = { workspace = true, features = ["host"] }
guest = { package = "aes-guest", path = "./guest" }

[package.metadata.cargo-machete]
ignored = ["jolt-inlines-aes"]
